name: "Snapcast Proxy"
version: "1.0.0"
slug: "snapcast_proxy"
description: "Proxies WebSocket traffic from HAOS to your Snapcast server."
arch:
  - aarch64
  - amd64
startup: services
host_network: true
options:
  target_host: "10.1.10.113"
  target_port: 1780
schema:
  target_host: str
  target_port: int
